export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

import { Header } from '../components/common/Header';
import styles from './layout.module.scss';
export default function CheckoutLayout({ children }: { children: React.ReactNode }) {
  return (
    <main className={styles.main}>
      <Header hasSearch={false} />
      {children}
    </main>
  );
}
