import type { Metadata } from 'next';

import { Header } from '../components/common/Header/index';

export const metadata: Metadata = {
  title: 'Главная',
  description: 'Generated by create next app',
};

export default function HomeLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <main>
      <Header />
      {children}
      {modal}
    </main>
  );
}
